name: Run on Push and Every Hour

on:
  push:           # Triggers the workflow on every push
  schedule:       # Scheduled to run every hour
    - cron: '0 * * * *'  # Runs at minute 0 of every hour (UTC time)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: github4women
      run: dotnet restore

    - name: Build project
      working-directory: github4women
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      working-directory: github4women
      run: dotnet test --no-build --verbosity normal
